apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  DJANGO_ENV: dockerized
  DEBUG: "1"
  DJANGO_ALLOWED_HOSTS: "*"
  DATABASE: postgres
  DB_ENGINE: "django.db.backends.postgresql"
  DB_DATABASE: kuberdb
  DB_HOST: postgres-service
  DB_PORT: "5432"